name: Cartel Auto Update

on:
  schedule:
    - cron: '0 * * * *' # Runs every 1 hour
  workflow_dispatch: # Allows you to manually refresh from the Actions tab

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Execute Update Script
        run: php update.php

      - name: Commit and Push Changes
        run: |
          git config --global user.name "Cartel-Bot"
          git config --global user.email "bot@cartellive.app"
          git add playlist.m3u
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto Update: $(date)" && git push)
