name: Hourly Playlist Update

on:
  schedule:
    - cron: '0 * * * *' # Every 1 hour
  workflow_dispatch: # Allows you to "Manually Refresh" from GitHub Actions tab

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Fetch and Process Playlist
        run: node update_playlist.js

      - name: Commit and Push Changes
        run: |
          git config --global user.name "Cartel-Bot"
          git config --global user.email "bot@cartel.live"
          git add playlist.m3u
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update Playlist: $(date -u)" && git push)
